config/routes.rb
Howdynghbr::Application.routes.draw do
  get "pages/index"

  devise_for :users

  resources :users 
  resources :meetups do
    resources :participations
  end

  resources :meetups

  resources :neighborhoods 
  resources :locations

   root :to => 'pages#index'

end

app/models/meetup.rb
class Meetup < ActiveRecord::Base
  belongs_to :user
  belongs_to :category, inverse_of: :meetups
  belongs_to :neighborhood, :inverse_of => :meetups
  has_many :participations
  has_many :reviews, :through => :participations
  belongs_to :location, inverse_of: :meetups
  acts_as_gmappable :process_geocoding => false

  attr_accessible :category_id, :description, :is_past, :meet_up_time, :user_id,
    :meetup_date, :meetup_time, :neighborhood_id, :neighborhood, :location_id

  validates_presence_of :user
  validates_presence_of :category
  validates_presence_of :neighborhood
  validates_presence_of :location
  validates_presence_of :meetup_time
  validates_presence_of :meetup_date

  def time
    meetup_time.strftime("%I:%M %p")
  end

  def date
    meetup_date.strftime("%D")
  end

  def hood
    neighborhood.name
  end

  def username
    user.user_name
  end

  def cat_name
    category.name
  end

  def in_words
    "#{user.user_name} wants to #{category.name}
      at #{location.name} in #{neighborhood.name} on #{meetup_date.strftime("%m/%d")}
      around #{meetup_time.strftime("%I:%M%p")}."
  end

  def in_words_past
    "#{category.name} at #{location.name} in #{neighborhood.name}"
  end

  def user_signed_up?(input_user)
    participations.where(user_id: input_user).present?
  end

  def is_host?(input_user)
    input_user.user_id == :user.user_id
  end

  def past?
    self.meetup_date.past?
  end

  def participation_for(user)
    participations.where(user_id: user).first
  end

  def gmaps4rails_address
    "#{location.street_address}, #{location.city}, #{location.state}, #{self.location.latitude}, #{self.location.longitude}"
  end


end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  def index
    @q = Meetup.search(params[:q])
    @meetups = @q.result(:distinct => true).select {|meetup| !meetup.past?}
    @markers = ""
    @meetups.each do |meetup| 
      @markers += meetup.location.to_gmaps4rails
    end
    swap_brackets(@markers)
  end

  def show
    @meetup = Meetup.find(params[:id])
    @participation = @meetup.participations.new
    @location = @meetup.location
    @json = @location.to_gmaps4rails
  end

  def new
    @meetup = Meetup.new
  end

  def create
    @meetup = Meetup.new(params[:meetup])
    @meetup.user = current_user
    if @meetup.save
      flash[:notice] = "Meetup succesfully created!"
      redirect_to meetup_path(@meetup)
    else
      flash[:notice] = "The Meetup was not succesfully created. Please try again."
      redirect_to new_meetup_path(@meetup)
    end
  end

  protected

  def swap_brackets(string)
      string.gsub!(/\]\[/,",")
  end

end

app/helpers/meetup_helper.rb
module MeetupHelper

  def add_map_for(markers = " ") 

    if markers.blank?
      @gmaps_options = {
        "map_options" => {
          "center_latitude" => 42.3583,
          "center_longitude" => -71.0603,
          "zoom" => 14
        }       
      }
      gmaps(@gmaps_options)
    else
    gmaps(
      "map_options" =>{
        :auto_zoom => true
        },
        "markers" => { 
          "data" => markers, 
          "options" => {
            "do_clustering" => true, 
            "clusterer_maxZoom" => 16} 
          }
    ) 
      end
    end

end

app/views/meetups/_form.html.erb
  <div class="devise_form_for">
    <fieldset>
      <%= simple_form_for @meetup do |f|%>
      <%= f.error_notification %>
      <%= f.input :meetup_date, :as => :string, :required => true, :label => "Date", input_html: {class: 'datepicker'} %>
      <%= f.input :meetup_time, :as => :string, :required => true, :label => "Time", input_html: {class: 'datepicker'} %>
        <br/>
        <%= f.association :category, :required => true, :label => "I want to..." %>
        <br/>
        <%= f.association :neighborhood, :required => true %>
        <br/>
        <%= f.association :location, collection: [], :required => true%>
        <br/>
        <%= f.input :description, :required => true %>

      <div class="form-actions">
      <%= f.button :submit %>
      </div>
    </fieldset>
  <% end %>
  </div>

app/views/meetups/_meetups_filters.html.erb
  <div class="devise_form_div">
    <div class="fieldset">
   <div class="row">
  <%= search_form_for @q do |f| %>
     <div class="large-4 columns">
    <%=f.label :neighborhood_name_eq, "Neighborhood" %>


      <%=f.select :neighborhood_name_eq, 
        options_for_select(
          Neighborhood.all.collect {|n| [n.name, n.name]}.unshift(["Select a neighborhood", nil]),
          selected: params[:q].try(:[],:neighborhood_name_eq),
          include_blank: true
        )
      %>
    </div>
    <div class="large-4 columns">
    <%=f.label :category_id_eq, "Category" %>


    <%=f.select :category_id_eq,
      Category.all.collect {|c| [c.name, c.id]},
      {include_blank: true}
      %>
    </div>
    <div class="large-1 columns">
      <%=f.submit%>
  </div>
  <% end %>
</div>
  </div>
</div>

app/views/meetups/_participants.html.erb
<div class="panel" id="participants">
  <h5>Who'll be there:</h5>
  <ul id="attendees">
    <% @meetup.participations.each do |p| %>
    	<li>
    		<%= link_to image_tag(avatar_url(p.user)) + " #{p.user_name}", 
    		user_path(p.user) if p.id!=nil %>
    	</li>
    <% end %>
  </ul>
</div>

app/views/meetups/_sign_up_cancel.html.erb
<% if @meetup.user_signed_up?(current_user) %>
  <h5> Change of plans? Can't go? It's ok. We wont hold it against you... </h5>
  <p>
    <%= link_to "Nevermind...", meetup_participation_path(@meetup, @meetup.participation_for(current_user)),
      :data => { :confirm => "Are you sure?" }, 
      :method => :delete 
    %>
  </p>
<% else %>
  <p>
    <%= form_for [@meetup, @participation] do |f| %>
      <%= f.submit "I'm in!" %>
    <% end %>
  </p>
<% end %>

app/views/meetups/index.html.erb
<%= render 'meetups_filters' %>
<%= add_map_for(@markers) %>

      <div class="row">
        <table>
          <thead>
            <tr>
              <th>Organizer</th>
              <th>Category</th>
              <th>Description</th>
              <th>Time</th>
              <th>Date</th>
              <th>Neighborhood</th>
            </tr>
          </thead>
          <% @meetups.each do |meetup| %>
          <tr>
            <td><%= meetup.username %></td>
            <td><%= meetup.cat_name %></td>
            <td><%= meetup.description %> </td>
            <td><%= meetup.time %></td>
            <td><%= meetup.date %></td>
            <td><%= meetup.hood %></td>
          </tr>
          <% end %>
        </table>


      </div>

app/views/meetups/new.html.erb
<div class="row">
	<div class="devise_form_div">
<h3>So you want to meet your neighbors...</h3>
<h4>What are the details?</h4>

<%= render 'form' %>

</div>
</div>

app/views/meetups/show.html.erb
<div class="row">

  <div class ="large-8 columns">
    <div class="devise_form_div">
      <h3> Meet Deets </h3>
      <h3><%= @meetup.in_words %></h3>
      <h4><%= @meetup.description %></h4>
      <% if @meetup.participations.empty? %>
        <p>
          "Nobody has signed up yet. Why don't you get the ball rolling?"
        </p>
      <% else %>
        <%= "#{pluralize(@meetup.participations.count, 'other')} are going." %>
      <% end %>
    <%= render 'sign_up_cancel' %>
    </div>
    <%= render 'participants' %>
  </div>
  <div class="large-4 columns" id="detail_map">
    <%= gmaps({
        "map_options" => { "auto_zoom" => false, "zoom"=>17},
        "markers"     => { "data" => @json }
      })
    %>
    <div class="devise_form_div" id="meetup_location_address">
      <%= "#{@location.name}" %>
      <br/>
      <%= "#{@location.full_address}"%>
    </div>
  </div>
</div>