config/routes.rb
Howdynghbr::Application.routes.draw do
  get "pages/index"

  devise_for :users

  resources :users 
  resources :meetups do
    resources :participations
  end

  resources :meetups

  resources :neighborhoods 
  resources :locations

   root :to => 'pages#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :meetups
  has_many :participations
  has_many :reviews, :through => :participations
  has_one :favorite_category
  has_one :category, :through => :favorite_category
  
  attr_accessible :email, :first_name, :last_name, :location, 
    :short_bio, :tag_line, :user_name, :id, :password, 
    :password_confirmation, :remember_me

  validates_presence_of :user_name
  validates_uniqueness_of :user_name
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :first_name
  validates_presence_of :last_name


  def past_attended
    past_attended = []
    self.participations.each do |p|
      if p.meetup.past?
        past_attended << p.meetup
      end
    end
    past_attended
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!
  inherit_resources
  actions :index, :show

  def show
  	@user = User.find(params[:id])
  	@past_attended = @user.past_attended
  end

end

app/views/users/index.html.erb
<div class="row">
  <table>
    <thead>
      <tr>
        <th>User Name</th>
        <th>Name</th>
        <th>Email</th>
        <th>Tag Line</th>
      </tr>
    </thead>
    <% if @users.first==nil%>
      <p>No users are registered.</p>
    <%else%>
      <% @users.each do |user| %>
      <tr>
        <td><%= user.user_name %></td>
        <td><%= [user.first_name, user.last_name].join(" ") %> </td>
        <td><%= user.email %></td>
        <td><%= user.tag_line %></td>
      </tr>
      <% end %>
    <% end %>

  </table>
</div>

app/views/users/show.html.erb
<div class="profile_content">
  <div class="row" id="profiles">
    <div class="large-4 column" id="user_gravatar">
      <%= image_tag avatar_url(@user) %>
    </div>
    <div class="large-6 column" id="profile_inner">

      <h3><%= @user.user_name %></h3>
      <h4><%= "#{@user.first_name} #{@user.last_name}"%> </h4>
      <h5><%= "#{@user.tag_line}"%> </h5>
      <p> <%= @user.short_bio %> </p>
    </div>
  </div>
</div>
<div class="row">
<div class="user_stats">
  <div class="devise_form_div">
    <div class="large-3 column">
      <h5>Meetups Created</h6>
      <h3><%= "#{@user.meetups.count}" %></h3>
    </div>
    <div class="large-3 column">
      <h5>Meetups Attended</h5>
      <h3><%= "#{@user.past_attended.count}" %></h3>
    </div>
  </div>
</div>
<div class="panel" id="past_attended">
  <h4><%= "Meetups #{@user.user_name} attended:" %></h4>
    <% @user.past_attended.each do |n| %>
    <p><%= "#{n.in_words_past}" %></p>
    <%end%>
</div>
<div class="panel" id="meetups_hosted">
  <h4><%= "Meetups #{@user.user_name} hosted:"%></h4>
    <% @user.meetups.each do |m| %>
    <p><%= link_to "#{m.in_words}", meetup_path(m) %></p>
    <% end %>
</div>
</div>