config/routes.rb
Howdynghbr::Application.routes.draw do
  get "pages/index"

  devise_for :users

  resources :users 
  resources :meetups do
    resources :participations
  end

  resources :meetups

  resources :neighborhoods 
  resources :locations

   root :to => 'pages#index'

end

app/views/layouts/_header.html.erb
<div class="contain-to-grid fixed">
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">  howdynghbr  </a></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>        
    </ul>
    <section class="top-bar-section">
        <ul class="left">
          <li>
            <%= 
              link_to('Browse Meetups', meetups_path)
            %>
          </li>
          <% if user_signed_in? %>
          <li>
            <%= link_to('New Meetup', new_meetup_path)  %>  
          </li>
          <% end %>
        </ul>
        <ul class="right">
         <%= render :partial => './devise/menu/registration_items' %>
         <%= render :partial => './devise/menu/login_items' %>
        </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en"> 
<head>
 <meta charset="utf-8" />


 <meta name="viewport" content="width=device-width, initial-scale=1.0" />

 <title><%= content_for?(:title) ? yield(:title) : "howdynghbr" %></title>

 <%= stylesheet_link_tag    "application" %>
 <%= csrf_meta_tags %>
</head>
<%= render './layouts/header' %>
<body>
  <div class="wrapper">

    <% if flash[:notice] %>
    <div data-alert class="alert-box">
      <div class="row">
        <%= flash[:notice] %>
      </div>    
      <a href="#" class="close">&times;</a>
    </div>
    <% elsif flash[:alert] %>
    <div data-alert class="alert-box">
      <div class="row">
        <%= flash[:alert] %>
      </div>    
      <a href="#" class="close">&times;</a>
    </div>
    <% end %>



    <%= yield %>

    <div class="push"></div>
  </div>

  <div id="footer">
    <div class="row">
      <p>Conjugation is not my strong poiont.</p>
    </div>
  </div>

</body>



<%= javascript_include_tag "application" %>
<%= yield :scripts %>
</html>